In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import kagglehub
from kagglehub import KaggleDatasetAdapter

# The big dataset of ultra-marathon running

In [81]:
df1 = pd.read_csv("data/TWO_CENTURIES_OF_UM_RACES.csv")
df1.head()

C:\Users\maria.liliu.martine\AppData\Local\Temp\ipykernel_5672\1755183687.py:1: DtypeWarning: Columns (0: Athlete average speed) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv("data/TWO_CENTURIES_OF_UM_RACES.csv")

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,06.01.2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0
1,2018,06.01.2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1
2,2018,06.01.2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2
3,2018,06.01.2018,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3
4,2018,06.01.2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4

In [ ]:
print(df1.columns)
print(df1.shape)
print(df1.isna().sum())

Index(['Year of event', 'Event dates', 'Event name', 'Event distance/length',
       'Event number of finishers', 'Athlete performance', 'Athlete club',
       'Athlete country', 'Athlete year of birth', 'Athlete gender',
       'Athlete age category', 'Athlete average speed', 'Athlete ID'],
      dtype='str')
(7461195, 13)
Year of event                      0
Event dates                        0
Event name                         0
Event distance/length           1053
Event number of finishers          0
Athlete performance                2
Athlete club                 2826524
Athlete country                    3
Athlete year of birth         588161
Athlete gender                     7
Athlete age category          584938
Athlete average speed            224
Athlete ID                         0
dtype: int64

:

In [85]:
df1_clean = df1.dropna(subset=['Athlete age category'])
df1_clean = df1_clean.drop(columns=['Athlete club'])
print(df1_clean.shape)
print(df1_clean.isna().sum())

(6876257, 12)
Year of event                   0
Event dates                     0
Event name                      0
Event distance/length         968
Event number of finishers       0
Athlete performance             0
Athlete country                 0
Athlete year of birth        3421
Athlete gender                  0
Athlete age category            0
Athlete average speed         221
Athlete ID                      0
dtype: int64

In [ ]:
no_dist_events = df1_clean[df1_clean['Event distance/length'].isna()]
print(no_dist_events.shape)
print(no_dist_events['Event name'].value_counts())
#print(df1_clean[(df1_clean['Event name']== 'Maratonmarschen Stockholm (SWE)') & ~(df1_clean['Event distance/length'].isna())])
 
df1_clean2 = df1_clean.dropna(subset=['Event distance/length']) # all events with missing distance are only from 2 different events, so we can drop them.
print(df1_clean2.shape)
print(df1_clean2.isna().sum())

(968, 12)
Event name
Stockholm Fotrally (SWE)           794
Maratonmarschen Stockholm (SWE)    174
Name: count, dtype: int64
(6875289, 12)
Year of event                   0
Event dates                     0
Event name                      0
Event distance/length           0
Event number of finishers       0
Athlete performance             0
Athlete country                 0
Athlete year of birth        3421
Athlete gender                  0
Athlete age category            0
Athlete average speed         221
Athlete ID                      0
dtype: int64

# Finishers Boston Marathon 2015, 2016 & 2017

In [23]:
df21 = pd.read_csv("data/marathon_results_2015.csv")
df21 = df21.drop(df21.columns[0], axis=1)
df22 = pd.read_csv("data/marathon_results_2016.csv")
df23 = pd.read_csv("data/marathon_results_2017.csv")
df23 = df23.drop(df23.columns[0], axis=1)

In [36]:
print(df21.columns)

Index(['Bib', 'Name', 'Age', 'M/F', 'City', 'State', 'Country', 'Citizen',
       'Unnamed: 9', '5K', '10K', '15K', '20K', 'Half', '25K', '30K', '35K',
       '40K', 'Pace', 'Proj Time', 'Official Time', 'Overall', 'Gender',
       'Division'],
      dtype='str')

In [43]:
#col_name = 'Unnamed: 9' if 'Unnamed: 9' in df.columns else 'Unnamed: 8'
# rename the column to 'Parathletics' if it exists and replace NaN values with 'No'
def check_col(df):
    print(df.shape)
    col_name = 'Parathletics' 
    if col_name in df.columns:
        print(df[col_name].unique())
        #df[col_name] = df[col_name].fillna('No')
    else:
        print(f"Column '{col_name}' not found in the DataFrame.")
        print("Columns in the DataFrame:", df.columns)

print("Checking df21:")
check_col(df21)
print("Checking df22:")
check_col(df22)
print("Checking df23:")
check_col(df23)

Checking df21:
(26598, 24)
<StringArray>
['No', 'VI', 'MI']
Length: 3, dtype: str
Checking df22:
(26630, 24)
<StringArray>
['No', 'VI', 'MI']
Length: 3, dtype: str
Checking df23:
(26410, 24)
<StringArray>
['No', 'VI', 'MI']
Length: 3, dtype: str

In [44]:
df21['Year'] = 2015
df22['Year'] = 2016
df23['Year'] = 2017

In [45]:
print(df21.columns)
print(df22.columns)
print(df23.columns)

Index(['Bib', 'Name', 'Age', 'M/F', 'City', 'State', 'Country', 'Citizen',
       'Parathletics', '5K', '10K', '15K', '20K', 'Half', '25K', '30K', '35K',
       '40K', 'Pace', 'Proj Time', 'Official Time', 'Overall', 'Gender',
       'Division', 'Year'],
      dtype='str')
Index(['Bib', 'Name', 'Age', 'M/F', 'City', 'State', 'Country', 'Citizen',
       'Parathletics', '5K', '10K', '15K', '20K', 'Half', '25K', '30K', '35K',
       '40K', 'Pace', 'Proj Time', 'Official Time', 'Overall', 'Gender',
       'Division', 'Year'],
      dtype='str')
Index(['Bib', 'Name', 'Age', 'M/F', 'City', 'State', 'Country', 'Citizen',
       'Parathletics', '5K', '10K', '15K', '20K', 'Half', '25K', '30K', '35K',
       '40K', 'Pace', 'Proj Time', 'Official Time', 'Overall', 'Gender',
       'Division', 'Year'],
      dtype='str')

In [ ]:
df2 = pd.concat([df21, df22, df23], ignore_index=True)

print(df2.head())
print(df2['Year'].value_counts())

pd.DataFrame.to_csv(df2, "data/all_marathons_results.csv", index=False)

  Bib                   Name  Age M/F         City State Country Citizen  \
0   3         Desisa, Lelisa   25   M         Ambo   NaN     ETH     NaN
1   4  Tsegay, Yemane Adhane   30   M  Addis Ababa   NaN     ETH     NaN
2   8         Chebet, Wilson   29   M     Marakwet   NaN     KEN     NaN
3  11       Kipyego, Bernard   28   M      Eldoret   NaN     KEN     NaN
4  10          Korir, Wesley   32   M       Kitale   NaN     KEN     NaN

  Parathletics       5K  ...      30K      35K      40K     Pace Proj Time  \
0           No  0:14:43  ...  1:32:00  1:47:59  2:02:39  0:04:56         -
1           No  0:14:43  ...  1:31:59  1:47:59  2:02:42  0:04:58         -
2           No  0:14:43  ...  1:32:00  1:47:59  2:03:01  0:04:59         -
3           No  0:14:43  ...  1:32:00  1:48:03  2:03:47  0:05:00         -
4           No  0:14:43  ...  1:32:00  1:47:59  2:03:27  0:05:00         -

  Official Time Overall Gender Division  Year
0       2:09:17       1      1        1  2015
1       2:09:48       2      2        2  2015
2       2:10:22       3      3        3  2015
3       2:10:47       4      4        4  2015
4       2:10:49       5      5        5  2015

[5 rows x 25 columns]
Year
2016    26630
2015    26598
2017    26410
Name: count, dtype: int64

In [ ]:
df2.isna().sum()

# all na state values are in USA and CANada.

Bib                  0
Name                 0
Age                  0
M/F                  0
City                 1
State             8993
Country              0
Citizen          76198
Parathletics         0
5K                   0
10K                  0
15K                  0
20K                  0
Half                 0
25K                  0
30K                  0
35K                  0
40K                  0
Pace                 0
Proj Time            0
Official Time        0
Overall              0
Gender               0
Division             0
Year                 0
dtype: int64

# Marathon Data 2000-2019

In [ ]:
df3 = pd.read_csv("data/all_marathons_final.csv")

C:\Users\maria.liliu.martine\AppData\Local\Temp\ipykernel_5672\977091424.py:1: DtypeWarning: Columns (0: Gun Time, 1: Place, 2: Sex Place, 3: Sex1, 4: Country) have mixed types. Specify dtype option on import or set low_memory=False.
  df3 = pd.read_csv("data/all_marathons_final.csv")

,count,mean,std,min,25%,50%,75%,max
index,3343216.0,54.745752,180.461859,0.00,24.00,49.00,74.000000,10866.0
Age,2874339.0,38.398981,11.210327,0.00,30.00,38.00,46.000000,1810.0
Div Place,3237680.0,975.248719,1093.004484,0.00,230.00,599.00,1312.000000,8756.0
Time,3343216.0,289.540988,69.935568,123.75,239.75,278.35,325.766667,1051.8
Year,3343216.0,2010.178266,5.697181,2000.00,2005.00,2010.00,2015.000000,2019.0

In [16]:
df3.head()

,index,Name,Sex,Age,Gun Time,Place,Sex Place,Div Place,Sex1,Agegroup,Time,Country,data,Year,Marathon
0,8,SERGEI FEDOTOV,M,27.0,2:12:40,1,1,1.0,M,18-34,132.633333,"ROCKVILLE,","MD, USA",2000,Twin_Cities
1,0,EZAEL TLHOBO,M,36.0,2:12:43,2,2,1.0,M,35-39,132.683333,PORT,ELIZABETH,2000,Twin_Cities
2,1,JOSHUA KIPKEMBOI,M,41.0,2:12:46,3,3,1.0,M,40-44,132.716667,"CONCORD,","MA, USA",2000,Twin_Cities
3,2,PAVEL ANDREEV,M,30.0,2:12:48,4,4,1.0,M,18-34,132.766667,"MOSCOW,",Russia,2000,Twin_Cities
4,3,ELIAS CHELANGA,M,36.0,2:12:49,5,5,2.0,M,35-39,132.783333,"CONCORD,","MA, USA",2000,Twin_Cities

In [74]:
print(df3.columns)
print(df3.shape)
print(df3.isna().sum())

Index(['index', 'Name', 'Sex', 'Age', 'Gun Time', 'Place', 'Sex Place',
       'Div Place', 'Sex1', 'Agegroup', 'Time', 'Country', 'data', 'Year',
       'Marathon'],
      dtype='str')
(3343216, 15)
index              0
Name               9
Sex                0
Age           468877
Gun Time     1618149
Place           2796
Sex Place       5515
Div Place     105536
Sex1          152445
Agegroup        3096
Time               0
Country      1698955
data           70885
Year               0
Marathon           0
dtype: int64

In [119]:
print(df1_clean2.shape)
print(df2.shape)
print(df3.shape)

(6875289, 12)
(79638, 25)
(3343216, 15)